### ISSUE TITLE
ReferenceError: serielport is not defined when using AMBER Stick

### ISSUE THREAD

**Issue by AndreasTheCat** [sunsetdk/node-red-contrib-wmbus-client#10]
Sir,

expirienced error: 
`30 Dec 14:26:19 - [error] [wmbus-dongle:237369f3f07e58fc] ReferenceError: serielport is not defined`
when using the Amber Stick on Win10. 
Error does not not show up at the ImSt-Stick, but of course I do not own one.
Any help would be fine :-)

Yours, A.

**Comment by sunsetdk** [comment]
Has this worked before or has it just started failing now?

**Comment by AndreasTheCat** [comment]
Look at 

line 59 in wmbus-client/lib/client/telegramClient.js (seriel**P**ort is the correct variable name)

which you reference

**Comment by sunsetdk** [comment]
Thanks. I have comittet it. i will need to public a new version. but as i refer my specific version you may be albe to just reinstall that node.
