### ISSUE TITLE
TypeError: "path" is not defined: undefined

### ISSUE THREAD

**Issue by vukmirovic98** [sunsetdk/node-red-contrib-wmbus-client#13]
Trying to set up iM871A via wmbus-client on a raspberry pi!, the device is connected to USB, but when configuring I get port as undefined (check image).
![image](https://user-images.githubusercontent.com/53474043/168817549-9567d462-d6b7-4cb9-b0df-53be11b8627f.png)

![image](https://user-images.githubusercontent.com/53474043/168817470-a5e6696a-6035-4388-adbe-c0a8835ff719.png)
When deploying I get the error from the tittle!

**Comment by sunsetdk** [comment]
I'll have a look at it. I redid the code, but i managed to break it.

**Comment by vukmirovic98** [comment]
Did you managed to look at it?

**Comment by tommyhagenes** [comment]
Same issue here aswell. Is this fixable @sunsetdk?

**Comment by sunsetdk** [comment]
Please check if the problem is solved now :)
