### ISSUE TITLE
Monitor multiple meters

### ISSUE THREAD

**Issue by ginodecock** [sunsetdk/node-red-contrib-wmbus-client#2]
Hi,

In the node properties you need to enter the serial number of the watermeter.

Can you use multiple kamstrup 21 nodes with one dongle to monitor multiple meters?
Can you disable this filter based on serial number and let every message pass in order to filter based on database records?

Thanks,
Gino

**Comment by sunsetdk** [comment]
Hi 
You just need to node, each using the same config node. But each node is for one meter. But insert 2 nodes with different serial numbers.

René
