### ISSUE TITLE
Error when installing palette

### ISSUE THREAD

**Issue by MTrab** [sunsetdk/node-red-contrib-wmbus-client#3]
When I try to install from the palette in Node-RED, I get this error in the debug window.

> node-crc@1.2.2 install /config/node-red/node_modules/node-crc
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /config/node-red/node_modules/node-crc
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code E...

**Comment by sunsetdk** [comment]
Does this issue still exist with the newer versions?

**Comment by MTrab** [comment]
Still have it today.

**Comment by MTrab** [comment]
After some further investigation, it seems like the cause for this error is the Node-Red Docker image for HassIO - some build-essentials is missing.

**Comment by MTrab** [comment]
Can you perhaps tell me what dependencies this module have?

**Comment by MTrab** [comment]
Okay - getting a step closer.
Now I'm stranded on installing an old serialports package (6.2.2) - could you update dependencies to accept a newer version?

**Comment by sunsetdk** [comment]
I'll attempt to have a look tomorrow.
But i can see that i do allow a slightly newer version than 6.2.2. I do allow all newer minor versions of serialport. Bu i need to check if i can move to the newest.

**Comment by sunsetdk** [comment]
Shold be fixed
