### ISSUE TITLE
Can't add node to node-red

### ISSUE THREAD

**Issue by Stefananderssonster** [sunsetdk/node-red-contrib-wmbus-client#5]
Hello,
I tried to add this component to my node-red installation (version 1.0.4) running on a RPI 3b+ but get a lot of errors. I saw that someone had proberly the same problem in a previous issue. Can this be fixed in some way. Can I use a older version of node-red and get it working?  Which version was it tested on?

**Comment by iSamBa** [comment]
Hello @Stefananderssonster 
I have solved that problem, and made a pull request to integrate the changes to repository, I am waiting for the owner to complete this PR.
If you need the updated version, you can clone it from my repository.

**Comment by sunsetdk** [comment]
Solved i assume
