### ISSUE TITLE
HOW-TO USE: Prepare RPi for use with this wm-bus node - sollution

### ISSUE THREAD

**Issue by jinx17** [sunsetdk/node-red-contrib-wmbus-client#7]
I use DietPi as OS on my RPi's.
When installing latest versions I found out it installs Node v14.xxx, which causes problems when installing wmbus-client node.
Let's say node-red is allready installed.
This node uses Serialport v6.2.2 which **can not be installed in Node v14.xxx and v12.xxx**
So node should be downgraded to v10.22.0.
How to do this:
Check what node version is installed with node-red: `node -v`
If version is higher than v10, then follow below:
Remove serialport if exists:    `npm remove serialport`
First install "n" package with npm like this:     `npm install –g n `
Downgrade "node" to version 10.22 (and npe v6.14.6) like this:   `sudo n 10.22.0`
Check node version with command: `node -v`
restart RPi: `restart`
When rebooted, open web page of node-red, go to manage pallete and install "node-red-contrib-wmbus-client"
Now you should see nodes present in node-red, and you can also select com port (USB) in config.

**Comment by sunsetdk** [comment]
This should now be fixed (better late than never)
